// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO2

package ctitc.seagoing.SEAGOING



sealed trait RriverType extends _root_.com.trueaccord.scalapb.GeneratedEnum {
  type EnumType = RriverType
  def isvehiclePosition: Boolean = false
  def isvehTermRegVehTermReg: Boolean = false
  def isvehicleDriverInfo: Boolean = false
  def isvehicleEwayBill: Boolean = false
  def isvehBaseInfo: Boolean = false
  def isproviderInfo: Boolean = false
  def companion: _root_.com.trueaccord.scalapb.GeneratedEnumCompanion[RriverType] = ctitc.seagoing.SEAGOING.RriverType
}

object RriverType extends _root_.com.trueaccord.scalapb.GeneratedEnumCompanion[RriverType] {
  implicit def enumCompanion: _root_.com.trueaccord.scalapb.GeneratedEnumCompanion[RriverType] = this
  @SerialVersionUID(0L)
  case object vehiclePosition extends RriverType {
    val value = 4097
    val index = 0
    val name = "vehiclePosition"
    override def isvehiclePosition: Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object vehTermRegVehTermReg extends RriverType {
    val value = 4098
    val index = 1
    val name = "vehTermRegVehTermReg"
    override def isvehTermRegVehTermReg: Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object vehicleDriverInfo extends RriverType {
    val value = 4099
    val index = 2
    val name = "vehicleDriverInfo"
    override def isvehicleDriverInfo: Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object vehicleEwayBill extends RriverType {
    val value = 4100
    val index = 3
    val name = "vehicleEwayBill"
    override def isvehicleEwayBill: Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object vehBaseInfo extends RriverType {
    val value = 4101
    val index = 4
    val name = "vehBaseInfo"
    override def isvehBaseInfo: Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object providerInfo extends RriverType {
    val value = 4102
    val index = 5
    val name = "providerInfo"
    override def isproviderInfo: Boolean = true
  }
  
  @SerialVersionUID(0L)
  case class Unrecognized(value: Int) extends RriverType with _root_.com.trueaccord.scalapb.UnrecognizedEnum
  
  lazy val values = scala.collection.Seq(vehiclePosition, vehTermRegVehTermReg, vehicleDriverInfo, vehicleEwayBill, vehBaseInfo, providerInfo)
  def fromValue(value: Int): RriverType = value match {
    case 4097 => vehiclePosition
    case 4098 => vehTermRegVehTermReg
    case 4099 => vehicleDriverInfo
    case 4100 => vehicleEwayBill
    case 4101 => vehBaseInfo
    case 4102 => providerInfo
    case __other => Unrecognized(__other)
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.EnumDescriptor = SEAGOINGProto.javaDescriptor.getEnumTypes.get(0)
  def scalaDescriptor: _root_.scalapb.descriptors.EnumDescriptor = SEAGOINGProto.scalaDescriptor.enums(0)
}