// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO2

package ctitc.seagoing.SEAGOING



/** 驾驶员身份信息
  *
  * @param vehicleNo
  *   车牌号码
  * @param plateColor
  *   车牌颜色	
  * @param accessCode
  *   车辆归属省行政区域编码
  * @param driverName
  *   驾驶员姓名
  * @param driverId
  *   身份证编号
  * @param licence
  *   从业资格证号
  * @param orgName
  *   发证机构名称
  * @param reserved
  *   备注
  */
@SerialVersionUID(0L)
final case class VehicleDriverInfo(
    vehicleNo: String,
    plateColor: scala.Option[Int] = None,
    accessCode: scala.Option[Int] = None,
    driverName: scala.Option[String] = None,
    driverId: scala.Option[String] = None,
    licence: scala.Option[String] = None,
    orgName: scala.Option[String] = None,
    reserved: scala.Option[String] = None
    ) extends com.trueaccord.scalapb.GeneratedMessage with com.trueaccord.scalapb.Message[VehicleDriverInfo] with com.trueaccord.lenses.Updatable[VehicleDriverInfo] {
    @transient
    private[this] var __serializedSizeCachedValue: Int = 0
    private[this] def __computeSerializedValue(): Int = {
      var __size = 0
      __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(1, vehicleNo)
      if (plateColor.isDefined) { __size += _root_.com.google.protobuf.CodedOutputStream.computeInt32Size(2, plateColor.get) }
      if (accessCode.isDefined) { __size += _root_.com.google.protobuf.CodedOutputStream.computeUInt32Size(3, accessCode.get) }
      if (driverName.isDefined) { __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(4, driverName.get) }
      if (driverId.isDefined) { __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(5, driverId.get) }
      if (licence.isDefined) { __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(6, licence.get) }
      if (orgName.isDefined) { __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(7, orgName.get) }
      if (reserved.isDefined) { __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(8, reserved.get) }
      __size
    }
    final override def serializedSize: Int = {
      var read = __serializedSizeCachedValue
      if (read == 0) {
        read = __computeSerializedValue()
        __serializedSizeCachedValue = read
      }
      read
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): Unit = {
      _output__.writeString(1, vehicleNo)
      plateColor.foreach { __v =>
        _output__.writeInt32(2, __v)
      };
      accessCode.foreach { __v =>
        _output__.writeUInt32(3, __v)
      };
      driverName.foreach { __v =>
        _output__.writeString(4, __v)
      };
      driverId.foreach { __v =>
        _output__.writeString(5, __v)
      };
      licence.foreach { __v =>
        _output__.writeString(6, __v)
      };
      orgName.foreach { __v =>
        _output__.writeString(7, __v)
      };
      reserved.foreach { __v =>
        _output__.writeString(8, __v)
      };
    }
    def mergeFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): ctitc.seagoing.SEAGOING.VehicleDriverInfo = {
      var __vehicleNo = this.vehicleNo
      var __plateColor = this.plateColor
      var __accessCode = this.accessCode
      var __driverName = this.driverName
      var __driverId = this.driverId
      var __licence = this.licence
      var __orgName = this.orgName
      var __reserved = this.reserved
      var __requiredFields0: Long = 0x1L
      var _done__ = false
      while (!_done__) {
        val _tag__ = _input__.readTag()
        _tag__ match {
          case 0 => _done__ = true
          case 10 =>
            __vehicleNo = _input__.readString()
            __requiredFields0 &= 0xfffffffffffffffeL
          case 16 =>
            __plateColor = Some(_input__.readInt32())
          case 24 =>
            __accessCode = Some(_input__.readUInt32())
          case 34 =>
            __driverName = Some(_input__.readString())
          case 42 =>
            __driverId = Some(_input__.readString())
          case 50 =>
            __licence = Some(_input__.readString())
          case 58 =>
            __orgName = Some(_input__.readString())
          case 66 =>
            __reserved = Some(_input__.readString())
          case tag => _input__.skipField(tag)
        }
      }
      if (__requiredFields0 != 0L) { throw new _root_.com.google.protobuf.InvalidProtocolBufferException("Message missing required fields.") } 
      ctitc.seagoing.SEAGOING.VehicleDriverInfo(
          vehicleNo = __vehicleNo,
          plateColor = __plateColor,
          accessCode = __accessCode,
          driverName = __driverName,
          driverId = __driverId,
          licence = __licence,
          orgName = __orgName,
          reserved = __reserved
      )
    }
    def withVehicleNo(__v: String): VehicleDriverInfo = copy(vehicleNo = __v)
    def getPlateColor: Int = plateColor.getOrElse(0)
    def clearPlateColor: VehicleDriverInfo = copy(plateColor = None)
    def withPlateColor(__v: Int): VehicleDriverInfo = copy(plateColor = Some(__v))
    def getAccessCode: Int = accessCode.getOrElse(0)
    def clearAccessCode: VehicleDriverInfo = copy(accessCode = None)
    def withAccessCode(__v: Int): VehicleDriverInfo = copy(accessCode = Some(__v))
    def getDriverName: String = driverName.getOrElse("")
    def clearDriverName: VehicleDriverInfo = copy(driverName = None)
    def withDriverName(__v: String): VehicleDriverInfo = copy(driverName = Some(__v))
    def getDriverId: String = driverId.getOrElse("")
    def clearDriverId: VehicleDriverInfo = copy(driverId = None)
    def withDriverId(__v: String): VehicleDriverInfo = copy(driverId = Some(__v))
    def getLicence: String = licence.getOrElse("")
    def clearLicence: VehicleDriverInfo = copy(licence = None)
    def withLicence(__v: String): VehicleDriverInfo = copy(licence = Some(__v))
    def getOrgName: String = orgName.getOrElse("")
    def clearOrgName: VehicleDriverInfo = copy(orgName = None)
    def withOrgName(__v: String): VehicleDriverInfo = copy(orgName = Some(__v))
    def getReserved: String = reserved.getOrElse("")
    def clearReserved: VehicleDriverInfo = copy(reserved = None)
    def withReserved(__v: String): VehicleDriverInfo = copy(reserved = Some(__v))
    def getFieldByNumber(__fieldNumber: Int): scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => vehicleNo
        case 2 => plateColor.orNull
        case 3 => accessCode.orNull
        case 4 => driverName.orNull
        case 5 => driverId.orNull
        case 6 => licence.orNull
        case 7 => orgName.orNull
        case 8 => reserved.orNull
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PString(vehicleNo)
        case 2 => plateColor.map(_root_.scalapb.descriptors.PInt(_)).getOrElse(_root_.scalapb.descriptors.PEmpty)
        case 3 => accessCode.map(_root_.scalapb.descriptors.PInt(_)).getOrElse(_root_.scalapb.descriptors.PEmpty)
        case 4 => driverName.map(_root_.scalapb.descriptors.PString(_)).getOrElse(_root_.scalapb.descriptors.PEmpty)
        case 5 => driverId.map(_root_.scalapb.descriptors.PString(_)).getOrElse(_root_.scalapb.descriptors.PEmpty)
        case 6 => licence.map(_root_.scalapb.descriptors.PString(_)).getOrElse(_root_.scalapb.descriptors.PEmpty)
        case 7 => orgName.map(_root_.scalapb.descriptors.PString(_)).getOrElse(_root_.scalapb.descriptors.PEmpty)
        case 8 => reserved.map(_root_.scalapb.descriptors.PString(_)).getOrElse(_root_.scalapb.descriptors.PEmpty)
      }
    }
    override def toString: String = _root_.com.trueaccord.scalapb.TextFormat.printToUnicodeString(this)
    def companion = ctitc.seagoing.SEAGOING.VehicleDriverInfo
}

object VehicleDriverInfo extends com.trueaccord.scalapb.GeneratedMessageCompanion[ctitc.seagoing.SEAGOING.VehicleDriverInfo] {
  implicit def messageCompanion: com.trueaccord.scalapb.GeneratedMessageCompanion[ctitc.seagoing.SEAGOING.VehicleDriverInfo] = this
  def fromFieldsMap(__fieldsMap: scala.collection.immutable.Map[_root_.com.google.protobuf.Descriptors.FieldDescriptor, scala.Any]): ctitc.seagoing.SEAGOING.VehicleDriverInfo = {
    require(__fieldsMap.keys.forall(_.getContainingType() == javaDescriptor), "FieldDescriptor does not match message type.")
    val __fields = javaDescriptor.getFields
    ctitc.seagoing.SEAGOING.VehicleDriverInfo(
      __fieldsMap(__fields.get(0)).asInstanceOf[String],
      __fieldsMap.get(__fields.get(1)).asInstanceOf[scala.Option[Int]],
      __fieldsMap.get(__fields.get(2)).asInstanceOf[scala.Option[Int]],
      __fieldsMap.get(__fields.get(3)).asInstanceOf[scala.Option[String]],
      __fieldsMap.get(__fields.get(4)).asInstanceOf[scala.Option[String]],
      __fieldsMap.get(__fields.get(5)).asInstanceOf[scala.Option[String]],
      __fieldsMap.get(__fields.get(6)).asInstanceOf[scala.Option[String]],
      __fieldsMap.get(__fields.get(7)).asInstanceOf[scala.Option[String]]
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[ctitc.seagoing.SEAGOING.VehicleDriverInfo] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      require(__fieldsMap.keys.forall(_.containingMessage == scalaDescriptor), "FieldDescriptor does not match message type.")
      ctitc.seagoing.SEAGOING.VehicleDriverInfo(
        __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).get.as[String],
        __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).flatMap(_.as[scala.Option[Int]]),
        __fieldsMap.get(scalaDescriptor.findFieldByNumber(3).get).flatMap(_.as[scala.Option[Int]]),
        __fieldsMap.get(scalaDescriptor.findFieldByNumber(4).get).flatMap(_.as[scala.Option[String]]),
        __fieldsMap.get(scalaDescriptor.findFieldByNumber(5).get).flatMap(_.as[scala.Option[String]]),
        __fieldsMap.get(scalaDescriptor.findFieldByNumber(6).get).flatMap(_.as[scala.Option[String]]),
        __fieldsMap.get(scalaDescriptor.findFieldByNumber(7).get).flatMap(_.as[scala.Option[String]]),
        __fieldsMap.get(scalaDescriptor.findFieldByNumber(8).get).flatMap(_.as[scala.Option[String]])
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = SEAGOINGProto.javaDescriptor.getMessageTypes.get(3)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = SEAGOINGProto.scalaDescriptor.messages(3)
  def messageCompanionForFieldNumber(__fieldNumber: Int): _root_.com.trueaccord.scalapb.GeneratedMessageCompanion[_] = throw new MatchError(__fieldNumber)
  def enumCompanionForFieldNumber(__fieldNumber: Int): _root_.com.trueaccord.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = ctitc.seagoing.SEAGOING.VehicleDriverInfo(
    vehicleNo = ""
  )
  implicit class VehicleDriverInfoLens[UpperPB](_l: _root_.com.trueaccord.lenses.Lens[UpperPB, ctitc.seagoing.SEAGOING.VehicleDriverInfo]) extends _root_.com.trueaccord.lenses.ObjectLens[UpperPB, ctitc.seagoing.SEAGOING.VehicleDriverInfo](_l) {
    def vehicleNo: _root_.com.trueaccord.lenses.Lens[UpperPB, String] = field(_.vehicleNo)((c_, f_) => c_.copy(vehicleNo = f_))
    def plateColor: _root_.com.trueaccord.lenses.Lens[UpperPB, Int] = field(_.getPlateColor)((c_, f_) => c_.copy(plateColor = Some(f_)))
    def optionalPlateColor: _root_.com.trueaccord.lenses.Lens[UpperPB, scala.Option[Int]] = field(_.plateColor)((c_, f_) => c_.copy(plateColor = f_))
    def accessCode: _root_.com.trueaccord.lenses.Lens[UpperPB, Int] = field(_.getAccessCode)((c_, f_) => c_.copy(accessCode = Some(f_)))
    def optionalAccessCode: _root_.com.trueaccord.lenses.Lens[UpperPB, scala.Option[Int]] = field(_.accessCode)((c_, f_) => c_.copy(accessCode = f_))
    def driverName: _root_.com.trueaccord.lenses.Lens[UpperPB, String] = field(_.getDriverName)((c_, f_) => c_.copy(driverName = Some(f_)))
    def optionalDriverName: _root_.com.trueaccord.lenses.Lens[UpperPB, scala.Option[String]] = field(_.driverName)((c_, f_) => c_.copy(driverName = f_))
    def driverId: _root_.com.trueaccord.lenses.Lens[UpperPB, String] = field(_.getDriverId)((c_, f_) => c_.copy(driverId = Some(f_)))
    def optionalDriverId: _root_.com.trueaccord.lenses.Lens[UpperPB, scala.Option[String]] = field(_.driverId)((c_, f_) => c_.copy(driverId = f_))
    def licence: _root_.com.trueaccord.lenses.Lens[UpperPB, String] = field(_.getLicence)((c_, f_) => c_.copy(licence = Some(f_)))
    def optionalLicence: _root_.com.trueaccord.lenses.Lens[UpperPB, scala.Option[String]] = field(_.licence)((c_, f_) => c_.copy(licence = f_))
    def orgName: _root_.com.trueaccord.lenses.Lens[UpperPB, String] = field(_.getOrgName)((c_, f_) => c_.copy(orgName = Some(f_)))
    def optionalOrgName: _root_.com.trueaccord.lenses.Lens[UpperPB, scala.Option[String]] = field(_.orgName)((c_, f_) => c_.copy(orgName = f_))
    def reserved: _root_.com.trueaccord.lenses.Lens[UpperPB, String] = field(_.getReserved)((c_, f_) => c_.copy(reserved = Some(f_)))
    def optionalReserved: _root_.com.trueaccord.lenses.Lens[UpperPB, scala.Option[String]] = field(_.reserved)((c_, f_) => c_.copy(reserved = f_))
  }
  final val VEHICLENO_FIELD_NUMBER = 1
  final val PLATECOLOR_FIELD_NUMBER = 2
  final val ACCESSCODE_FIELD_NUMBER = 3
  final val DRIVERNAME_FIELD_NUMBER = 4
  final val DRIVERID_FIELD_NUMBER = 5
  final val LICENCE_FIELD_NUMBER = 6
  final val ORGNAME_FIELD_NUMBER = 7
  final val RESERVED_FIELD_NUMBER = 8
}
